version: '3'

services:
    web:
        build:
            context: .
        volumes:
            - .:/var/www/bdoi
        working_dir: /var/www/bdoi
        command: ["bundle", "exec", "jekyll", "serve", "--host", "0.0.0.0"]
        ports:
            - "4000:4000"
